// Code generated by qtc from "WASM.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/WASM.html:1
package components

//line views/components/WASM.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/WASM.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/WASM.html:1
func StreamWASMScript(qw422016 *qt422016.Writer) {
//line views/components/WASM.html:1
	qw422016.N().S(`
<script src="/assets/wasm/wasm_exec.js" defer="defer"></script>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    if (!WebAssembly.instantiateStreaming) {
      WebAssembly.instantiateStreaming = async (resp, importObject) => {
        const source = await (await resp).arrayBuffer();
        return await WebAssembly.instantiate(source, importObject);
      };
    }

    const start = new Date().getTime();
    const go = new Go();
    WebAssembly.instantiateStreaming(fetch("/assets/wasm/solitaire.wasm"), go.importObject).then((result) => {
      go.run(result.instance);
      wasmInit(new Date().getTime() - start);
    });
  });
</script>
`)
//line views/components/WASM.html:20
}

//line views/components/WASM.html:20
func WriteWASMScript(qq422016 qtio422016.Writer) {
//line views/components/WASM.html:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/WASM.html:20
	StreamWASMScript(qw422016)
//line views/components/WASM.html:20
	qt422016.ReleaseWriter(qw422016)
//line views/components/WASM.html:20
}

//line views/components/WASM.html:20
func WASMScript() string {
//line views/components/WASM.html:20
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/WASM.html:20
	WriteWASMScript(qb422016)
//line views/components/WASM.html:20
	qs422016 := string(qb422016.B)
//line views/components/WASM.html:20
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/WASM.html:20
	return qs422016
//line views/components/WASM.html:20
}
