// Code generated by qtc from "WASM.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/WASM.html:1
package components

//line views/components/WASM.html:1
import (
	"github.com/kyleu/solitaire/app/util"
	"github.com/kyleu/solitaire/assets"
)

//line views/components/WASM.html:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/WASM.html:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/WASM.html:6
func StreamWASMScript(qw422016 *qt422016.Writer, cfg any, logger util.Logger) {
//line views/components/WASM.html:6
	qw422016.N().S(`
`)
//line views/components/WASM.html:7
	qw422016.N().S(assets.ScriptElement(`wasm/wasm_exec.js`, true, logger))
//line views/components/WASM.html:7
	qw422016.N().S(`
<script>
  document.addEventListener("DOMContentLoaded", function() {
    if (!WebAssembly.instantiateStreaming) {
      WebAssembly.instantiateStreaming = async (resp, importObject) => {
        const source = await (await resp).arrayBuffer();
        return await WebAssembly.instantiate(source, importObject);
      };
    }

    const start = new Date().getTime();
    const go = new Go();
    WebAssembly.instantiateStreaming(fetch("`)
//line views/components/WASM.html:19
	qw422016.E().S(assets.URL(`wasm/solitaire.wasm`, logger))
//line views/components/WASM.html:19
	qw422016.N().S(`"), go.importObject).then((result) => {
      go.run(result.instance);
      wasmInit(new Date().getTime() - start, `)
//line views/components/WASM.html:21
	qw422016.N().S(util.ToJSONCompact(cfg))
//line views/components/WASM.html:21
	qw422016.N().S(`);
    });
  });
</script>
`)
//line views/components/WASM.html:25
}

//line views/components/WASM.html:25
func WriteWASMScript(qq422016 qtio422016.Writer, cfg any, logger util.Logger) {
//line views/components/WASM.html:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/WASM.html:25
	StreamWASMScript(qw422016, cfg, logger)
//line views/components/WASM.html:25
	qt422016.ReleaseWriter(qw422016)
//line views/components/WASM.html:25
}

//line views/components/WASM.html:25
func WASMScript(cfg any, logger util.Logger) string {
//line views/components/WASM.html:25
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/WASM.html:25
	WriteWASMScript(qb422016, cfg, logger)
//line views/components/WASM.html:25
	qs422016 := string(qb422016.B)
//line views/components/WASM.html:25
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/WASM.html:25
	return qs422016
//line views/components/WASM.html:25
}
