// Code generated by qtc from "HTML.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vgame/HTML.html:1
package vgame

//line views/vgame/HTML.html:1
import (
	"github.com/kyleu/solitaire/app"
	"github.com/kyleu/solitaire/app/controller/cutil"
	"github.com/kyleu/solitaire/app/game"
	"github.com/kyleu/solitaire/app/util"
	"github.com/kyleu/solitaire/views/components"
	"github.com/kyleu/solitaire/views/layout"
)

//line views/vgame/HTML.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vgame/HTML.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vgame/HTML.html:10
type HTML struct {
	layout.Basic
	Game *game.Game
}

//line views/vgame/HTML.html:15
func (p *HTML) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vgame/HTML.html:15
	qw422016.N().S(`
<div class="card">
  <h3>`)
//line views/vgame/HTML.html:17
	components.StreamSVGRefIcon(qw422016, `gift`, ps)
//line views/vgame/HTML.html:17
	qw422016.E().S(util.AppName)
//line views/vgame/HTML.html:17
	qw422016.N().S(` HTML</h3>
</div>
<div class="card">
  <h3>Game</h3>
  <div style="font-size: 500%;">
`)
//line views/vgame/HTML.html:22
	for _, c := range p.Game.Deck.Cards {
//line views/vgame/HTML.html:22
		qw422016.N().S(`    <span`)
//line views/vgame/HTML.html:23
		if c.Suit.Color().Name() == `Red` {
//line views/vgame/HTML.html:23
			qw422016.N().S(` style="color: red;"`)
//line views/vgame/HTML.html:23
		}
//line views/vgame/HTML.html:23
		qw422016.N().S(`>`)
//line views/vgame/HTML.html:23
		qw422016.E().S(c.Unicode())
//line views/vgame/HTML.html:23
		qw422016.N().S(`</span>
`)
//line views/vgame/HTML.html:24
	}
//line views/vgame/HTML.html:24
	qw422016.N().S(`  </div>
</div>
`)
//line views/vgame/HTML.html:27
}

//line views/vgame/HTML.html:27
func (p *HTML) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vgame/HTML.html:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vgame/HTML.html:27
	p.StreamBody(qw422016, as, ps)
//line views/vgame/HTML.html:27
	qt422016.ReleaseWriter(qw422016)
//line views/vgame/HTML.html:27
}

//line views/vgame/HTML.html:27
func (p *HTML) Body(as *app.State, ps *cutil.PageState) string {
//line views/vgame/HTML.html:27
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vgame/HTML.html:27
	p.WriteBody(qb422016, as, ps)
//line views/vgame/HTML.html:27
	qs422016 := string(qb422016.B)
//line views/vgame/HTML.html:27
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vgame/HTML.html:27
	return qs422016
//line views/vgame/HTML.html:27
}
