[package]
name = "solitaire-core"
version = "0.0.1"
authors = ["Kyle Unverferth <kyle@kyleu.com>"]
edition = "2018"
description = "Core classes used by solitaire in the app and WASM"
keywords = ["test", "noop", "pointless"]
homepage = "https://estimate.poker"
repository = "https://github.com/kyleu/solitaire"
license = "MIT"
build = "build.rs"

[build-dependencies]
built = "0.3.2"

[dependencies]
anyhow = "1.0.23"
bincode = "1.2.0"
derive_more = "0.99.2"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
